sudo: required
language: go
go:
- 1.8
install:
- bin/ci
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push orangeopensource/artifactory-resource; fi
env:
  global:
  - secure: GuLWAheAr3K+oKopYpsFtGMpE8sZfTObz649GBqszW5sl2MmcxHHN5zWodbpSuxF3ssIR2FMtgBba5OWarEZNHP4R83Lr0EG5hkyKr06WuRvzPrt3IvNa4jBeW7WKmzb+dCFDUQu2n3mDeC9sHk3nGjXKHxzSd4tSraeg9QDvXTjD+OVppAvZ1cYnzgelsiI2yb7zhYz5XZHN+hznvhy2zdo2qYPCwh8mFr/7UIy8VDcSX14AzoWD/Qytsah/rH4AG1LvdMo4Vg3QnBV1jQAmDJYUCwhFakjtwVccMtNILCs32UGFqfHcVuRbEGB+VpKIHYVW1zVYMREEos3/COzP5I0t3nJuB/oHxyYaKokFVorM9EilaEyNGgj5gzxRQnzMBjzJPa6PSbIOZ3h4DgtuqvY+Kn+dEypJ0BT6fsNKUteyThNGbvjEjtEzRNfXgu69Akr6ntsnIqTC9aLNKVAvZLmTXlUuKCS9C24lY6/z36Bpl7jnoFQNjGxCev3VO9dVdleDxa/giiO/bsbQWc10IBigEOo4mLq7J8eESrpI2IlRa7m+d6YdKahbmJCyIyppbuvXTJa8iq1PWc1nBrUG/0pm4emxgaqGkxrs1YJlfg1zwNStMir9iTB8KH08pJX/3ZRm0a82/yaUz9j45orzVug8kc0KGRQx9EyuR6hOdQ=
  - secure: AaekX8rwh4pVQAZTTzT2TDc4AY/JCb4cady+VVhsp+UOKz739NB+Ox70IrSJO7fCH4FwEiebodKWb4HAkRjaite4d0go/D4R3AOcPTDDENEMd4pqjfFeHIEA7yL9Sko26LjUu3qZG5mzIeJDB4clBu68IpXfwdyOP1aCUoTOyYzYqD9i0/slH3BLAMGET+nZkAWx6ViEJpzKH63vAKJu6OacAO7jPaB0Uah9+3ZQtgUYt3jG7g28xsLeVCfkvcHMBbh29T7gZ0iJf0bZVFHlRB9VUyR+pgnGhFkUV7Z51Hm5E+V7+S7UT8flyyOjEDy5ckX9JvjH3sbSq5ZentK1tuFSWG83S18sARrYV1TEyLDfnOr1ldQFGDE2HuRQBketZXzvuxTHx1i2VeDt+pYqhZSb9SWLXzK/gEhobgjFJXwuzbrCNEUZf/fIWcKHGrVmr6Bsjx4Y4kOgB88ZFQlKnERVsZ/NMbIg3Ic8VByzu2crrD/bSeGWG918XfdqnIpgEsE5kKJZuocMwQmtotSDFXxBKL/31Xnw/p2iDaMNkjjW2h8LdOfOTYxirfT0sUX1d7O42yvVclAh7I6BUHfhCEvU5NCvBfIWdwW18CiHK/cjxv3UGffs5nr73DnKUmjAFXWQz52neRYdvBynE3qFrTPCKq0BpbfmeQ9MSpMaR70=
